@ECHO OFF

SET LANG=csharp
SET COMPILER=win-cl-14.1
SET SOLAR_VERSION=0.9.0
SET XPCF_VERSION=2.5.0

IF NOT EXIST "%REMAKEN_PKG_ROOT%/packages/SolARBuild/%COMPILER%/SolARPipelineManager/%SOLAR_VERSION%/%LANG%" (
MKDIR "%REMAKEN_PKG_ROOT%/packages/SolARBuild/%COMPILER%/SolARPipelineManager/%SOLAR_VERSION%/%LANG%"
)
DEL /s /q "%REMAKEN_PKG_ROOT%\packages\SolARBuild\%COMPILER%\SolARPipelineManager\%SOLAR_VERSION%\%LANG%\*.*" > NUL

SWIG ^
 -c++ ^
 -%LANG% ^
 -fcompact -O ^
 -I./swig ^
 -I"%REMAKEN_PKG_ROOT%/packages/%COMPILER%/xpcf/%XPCF_VERSION%/interfaces" ^
 -I"%REMAKEN_PKG_ROOT%/packages/SolARBuild/%COMPILER%/SolARFramework/%SOLAR_VERSION%/interfaces" ^
 -DXPCF_USE_BOOST ^
 -DSWIG_CSHARP_NO_WSTRING_HELPER ^
 -namespace SolAR ^
 -outdir "%REMAKEN_PKG_ROOT%/packages/SolARBuild/%COMPILER%/SolARPipelineManager/%SOLAR_VERSION%/%LANG%" ^
 -o "src/SolARPluginPipelineManager_wrap.cpp" ^
 interfaces/SolARPipelineManager.i

:: MonoPInvokeCallback should be added to static method generated by SWIG while using IL2CPP
ECHO ---------------- Edit for Android support ----------------------
ECHO DIR : %REMAKEN_PKG_ROOT%/packages/SolARBuild/%COMPILER%/SolARPipelineManager/%SOLAR_VERSION%/%LANG%
PUSHD
CD /D %REMAKEN_PKG_ROOT%/packages/SolARBuild/%COMPILER%/SolARPipelineManager/%SOLAR_VERSION%/%LANG%
POWERSHELL -command "Get-ChildItem -Path .\ -Filter *PINVOKE.cs -Recurse -File -Name | ForEach-Object {echo """# $_""";[System.IO.File]::WriteAllText($_,([System.IO.File]::ReadAllText($_) -replace 'static void SetPending','[AOT.MonoPInvokeCallback(typeof(ExceptionDelegate))] static void SetPending' -replace 'static string CreateString','[AOT.MonoPInvokeCallback(typeof(SWIGStringDelegate))] static string CreateString'))}"
POPD

ECHO ------------------ sub Bat file completed -----------------------------
